### ISSUE TITLE
[Feature request]  Add a tfg list that automerges an specifically labeled PR if conditions are meet

### ISSUE THREAD

**Issue by addUsername** [narvikd/victor_robles_bot#5]
Hai,

### What

While playing around with GitHub actions, I've come with the idea that keeping stored a TFG (~=final degree project)  list is a valuable resource for newcomers students.

The way to do it could be something like having a gh-action that allows everyone add its own final-project-repo automatically. Then just one additional endpoint in [bot_endpoints.go](https://github.com/narvikd/victor_robles_bot/blob/master/bot_endpoints.go) replying with that TFG-List.md link should do the trick, I think it could  be a nice feature to have ( there are other ways to implement it...).

### How

[This repo](https://github.com/addUsername/gh-actions/tree/main) contains the gh-action, you could use it as playground 
(btw, **I need someone who make a valid PR** for testing purposes ..^^).

[main.js](https://github.com/addUsername/gh-actions/blob/main/.github/actions/Add_TFG/main.js) is who do the work, don't get too scared by that cute "callback-hell", it can be refactor...  as you can see add/modify tests is trivial, jobs could be added/divided (one for tests, another for the merge part..) and file format/Markdown could be enhanced pretty easy as well

Let me know your thoughts about this idea and if it worth it to post a PR

ty!

**Comment by narvikd** [comment]
It looks really really interesting, once you test it enough in your fork/repo and it's stable I will merge it.
One thing you should note is that sadly the telegram library I'm using doesn't seem to support Markdown, and I don't know any workarounds. If it's too much of a hassle to change/convert from Markdown to a normal HTML syntax, we could try to explore other venues.

Thanks for all the hard work!

**Comment by addUsername** [comment]
Yep, the format thing is not a problem, also reading the code seems that  `./cursosinfo/TFG-List.txt` fits perfectly,  I didn't notice that.

The only "drawback" may be losing the "readability" part, but depending on implementation it couldn't be needed. So.. 
**Which implementation do you prefer?**
1. (easy +) bot returns a link to `TFG-List.md` (my initial idea) 
2. (easy) bot returns the text from stored `TFG-List.txt` (same workflow as the others files)
3. (medium) bot fetchs `TFG-List.txt` from the repo and returns text
4. (medium +)  bot fetchs `TFG-List.md` from the repo, converts to .html syntax and returns text
5. (???) telebot.v2 says that it Markdown  [should work]( https://pkg.go.dev/gopkg.in/tucnak/telebot.v2#ParseMode), just saying.. I'm not digging in there
6. (hard) 2 files, 2 actions.  `TFG-List .md` is the file to be edited, 1st action is the same as described before and the second one auto updates `TFG-List.txt` which is what bot fetchs and returns as text

I'll try to clarify what I'm seeing
Option 1: is my favourite, no extra network calls but always in sync, no extra code in go and we have tables
Option 2: swaps sync for user experience, good enough but misses the whole point of automation
Option 4 > option 3: because yes
Option 5: nope
Option 6: I only see it as the winner if being in sync is required but fetching is not allowed (..performance reasons, maybe?)  so the action will upload the file directly to bot file system  instead commiting the file to github (difficulty == epic)

Of course, they are just some speculative ideas, I'm not pretending to define how this implementation has to be done or anything like that, the point is just narrowing the whole thing

Sorry for the menssage length

**Comment by narvikd** [comment]
I'm closing this because it doesn't seem to have any traction.

Please, be free to reopen it again.
