### ISSUE TITLE
Review status of cursosinfo/acceso_links.txt

### ISSUE THREAD

**Issue by narvikd** [narvikd/victor_robles_bot#6]
We were informed that the Murcia link was down. I have changed it to another one, but I am not sure if it has all the necessary information.
Check out all the links.

**Comment by narvikd** [comment]
Add Baleares.

**Comment by iyanv** [comment]
I've just created the pull request ensuring Murcia link was the correct one and adding the Baleares information.

**Comment by narvikd** [comment]
Closed as of: https://github.com/narvikd/victor_robles_bot/pull/7

Thanks again, @iyanv.
